<style>
    .diagnosticButton {
        font: bold 14px Arial;
        text-decoration: none;
        background-color: #EEEEEE;
        color: #333333;
        border-top: 1px solid #CCCCCC;
        border-right: 1px solid #333333;
        border-bottom: 1px solid #333333;
        border-left: 1px solid #CCCCCC;
        padding: 10px;
    }
    .diagnosticButton:hover {
        text-decoration: none;
    }
</style>
<a href='<?php echo $block->getUrlDiagnostic() ?>' target="_blank" class="diagnosticButton">Generar PDF de Diagnóstico</a>